[package]
name = "red"
version = "0.1.0"
authors = ["Daniel Bergey <bergey@simspace.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# clap = "2.33.3"
# clap-v3 = "3.0.0-beta.1"
structopt = "0.3.22"